"""FS25 Crop Calendar – web-based UI.

Starts a local HTTP server and opens the crop calendar editor in the default
browser.  No external web framework is required; the server is built on
Python's built-in ``http.server``.

Usage
-----
    # Launch the web UI (opens browser automatically)
    python -m src.crop_calendar

    # Pre-load an existing crop config
    python -m src.crop_calendar --config examples/wheat_config.json

    # Choose a different port or output directory
    python -m src.crop_calendar --port 8181 --output ./my_output

API endpoints (consumed by the browser page)
---------------------------------------------
    GET  /                        → Serve the editor SPA
    GET  /api/presets             → Return available preset names + zones (JSON)
    GET  /api/load?path=<file>    → Load a crop config JSON from disk
    POST /api/save                → Persist the current config to disk (JSON)
    POST /api/export-html         → Generate & save a standalone calendar HTML,
                                    returning the rendered HTML in the response
"""

from __future__ import annotations

import json
import os
import sys
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlparse, parse_qs

from .utils import (
    MONTH_ABBR,
    CLIMATE_ZONES,
    CROP_PRESETS,
    CalendarEntry,
    CropConfig,
    ensure_dir,
)

# ---------------------------------------------------------------------------
# Standalone calendar HTML export  (also called by crop_maker.py)
# ---------------------------------------------------------------------------

_EXPORT_CSS = """
<style>
  body{font-family:Arial,sans-serif;background:#1a1a2e;color:#eee;margin:0;padding:20px}
  h1{color:#e94560;text-align:center;margin-bottom:4px}
  p.subtitle{text-align:center;color:#aaa;margin-top:0}
  table{border-collapse:collapse;width:100%;margin-bottom:20px}
  th,td{border:1px solid #333;padding:8px 6px;text-align:center;min-width:52px}
  th{background:#16213e;font-size:.85em}
  td.zone-label{text-align:left;font-weight:bold;padding-left:10px;background:#16213e}
  .plant{background:#2d6a4f;color:#fff}
  .grow{background:#1b4332;color:#fff}
  .harvest{background:#d4a017;color:#000}
  .idle{background:#111;color:#555}
  .legend{display:flex;gap:20px;flex-wrap:wrap;margin:10px 0 20px;justify-content:center}
  .legend-item{display:flex;align-items:center;gap:6px;font-size:.9em}
  .swatch{width:18px;height:18px;border-radius:3px}
  .plant-sw{background:#2d6a4f}
  .grow-sw{background:#1b4332}
  .harvest-sw{background:#d4a017}
  .idle-sw{background:#111;border:1px solid #333}
  footer{text-align:center;color:#555;font-size:.8em;margin-top:40px}
</style>
"""


def _cell_class(month: int, entry: CalendarEntry) -> str:
    if month in entry.harvesting_months:
        return "harvest"
    if month in entry.growing_months:
        return "grow"
    if month in entry.planting_months:
        return "plant"
    return "idle"


def _build_export_table(entry: CalendarEntry) -> str:
    header = "".join(f"<th>{a}</th>" for a in MONTH_ABBR)
    cells = "".join(
        '<td class="{cls}">{lbl}</td>'.format(
            cls=_cell_class(m, entry),
            lbl=("P" if m in entry.planting_months
                 else "G" if m in entry.growing_months
                 else "H" if m in entry.harvesting_months
                 else "·"),
        )
        for m in range(1, 13)
    )
    return (
        "<table>"
        f"<tr><th>Zone</th>{header}</tr>"
        f'<tr><td class="zone-label">{entry.zone.capitalize()}</td>{cells}</tr>'
        "</table>"
    )


def generate_calendar_html(crop: CropConfig, output_dir: str | Path) -> Path:
    """Generate a standalone HTML calendar for *crop* and write it to *output_dir*.

    Returns the path to the written file.
    """
    tables = (
        "\n".join(_build_export_table(e) for e in crop.calendar)
        if crop.calendar
        else "<p>No calendar data defined.</p>"
    )
    html = (
        '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
        f"<title>FS25 Crop Calendar – {crop.name}</title>{_EXPORT_CSS}</head><body>"
        "<h1>FS25 Crop Calendar</h1>"
        f'<p class="subtitle">Crop: <strong>{crop.title}</strong>'
        f" &nbsp;|&nbsp; Preset: {crop.preset}</p>"
        '<div class="legend">'
        '<div class="legend-item"><div class="swatch plant-sw"></div> Planting</div>'
        '<div class="legend-item"><div class="swatch grow-sw"></div> Growing</div>'
        '<div class="legend-item"><div class="swatch harvest-sw"></div> Harvesting</div>'
        '<div class="legend-item"><div class="swatch idle-sw"></div> Idle</div>'
        "</div>"
        f"{tables}"
        "<footer>Generated by FS25 Crop Maker &mdash; "
        "https://github.com/zhult18/FS25_Crop-maker</footer>"
        "</body></html>"
    )
    out = ensure_dir(output_dir)
    dest = out / f"{crop.name}_calendar.html"
    dest.write_text(html, encoding="utf-8")
    return dest


# ---------------------------------------------------------------------------
# Web-app SPA HTML  (served by the local server at GET /)
# ---------------------------------------------------------------------------

_SPA_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FS25 Crop Calendar Editor</title>
<style>
  /* ── Reset & base ───────────────────────────────────────── */
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:"Segoe UI",Arial,sans-serif;background:#12121f;color:#e0e0e0;min-height:100vh}
  a{color:#e94560}

  /* ── Layout ─────────────────────────────────────────────── */
  header{background:#0f3460;padding:14px 24px;display:flex;align-items:center;gap:16px}
  header h1{color:#e94560;font-size:1.4rem;flex:1}
  header span{color:#aaa;font-size:.85rem}
  .container{display:flex;gap:0;min-height:calc(100vh - 54px)}
  aside{width:280px;min-width:220px;background:#16213e;padding:20px;border-right:1px solid #222;display:flex;flex-direction:column;gap:18px}
  main{flex:1;padding:24px;overflow-x:auto}

  /* ── Sidebar form ───────────────────────────────────────── */
  aside h2{font-size:1rem;color:#e94560;border-bottom:1px solid #e94560;padding-bottom:6px}
  .field{display:flex;flex-direction:column;gap:4px}
  .field label{font-size:.78rem;color:#aaa;text-transform:uppercase;letter-spacing:.05em}
  .field input,.field select{background:#0f1a2e;border:1px solid #334;color:#eee;
    padding:7px 10px;border-radius:5px;font-size:.9rem;outline:none;transition:border .2s}
  .field input:focus,.field select:focus{border-color:#e94560}
  .field select option{background:#0f1a2e}

  /* ── Buttons ────────────────────────────────────────────── */
  .btn{display:block;width:100%;padding:9px 14px;border:none;border-radius:6px;
    font-size:.88rem;font-weight:600;cursor:pointer;text-align:center;transition:opacity .15s}
  .btn:hover{opacity:.85}
  .btn-primary{background:#e94560;color:#fff}
  .btn-secondary{background:#2d6a4f;color:#fff}
  .btn-outline{background:transparent;border:1px solid #555;color:#ccc}
  .btn-group{display:flex;flex-direction:column;gap:8px;margin-top:auto}

  /* ── Calendar grid ──────────────────────────────────────── */
  .section-title{font-size:1.05rem;font-weight:700;color:#e94560;
    margin-bottom:14px;border-bottom:1px solid #2a2a3e;padding-bottom:6px}
  .calendar-wrap{overflow-x:auto}
  table.cal{border-collapse:collapse;min-width:600px}
  table.cal th,table.cal td{border:1px solid #2a2a3e;padding:0;text-align:center;height:44px}
  table.cal th{background:#16213e;font-size:.78rem;color:#aaa;padding:6px 4px;
    font-weight:600;text-transform:uppercase;letter-spacing:.04em;min-width:54px}
  th.zone-head{text-align:left;padding-left:10px;min-width:110px;width:110px;color:#e94560}
  td.zone-label{text-align:left;padding-left:10px;font-weight:600;color:#ccc;
    background:#16213e;cursor:default;font-size:.85rem}
  td.cell{cursor:pointer;user-select:none;transition:filter .1s;font-size:.78rem;font-weight:700}
  td.cell:hover{filter:brightness(1.25)}
  td.idle   {background:#111;color:#444}
  td.plant  {background:#2d6a4f;color:#d4edda}
  td.grow   {background:#1b4332;color:#a8d5b5}
  td.harvest{background:#d4a017;color:#000}

  /* ── Legend ─────────────────────────────────────────────── */
  .legend{display:flex;gap:18px;flex-wrap:wrap;margin-bottom:18px;align-items:center}
  .legend-item{display:flex;align-items:center;gap:6px;font-size:.82rem;color:#ccc}
  .swatch{width:16px;height:16px;border-radius:3px;flex-shrink:0}
  .sw-idle{background:#111;border:1px solid #444}
  .sw-plant{background:#2d6a4f}
  .sw-grow{background:#1b4332}
  .sw-harvest{background:#d4a017}
  .legend .tip{margin-left:auto;font-size:.78rem;color:#666;font-style:italic}

  /* ── Toast notifications ────────────────────────────────── */
  #toast{position:fixed;bottom:28px;left:50%;transform:translateX(-50%);
    background:#222;color:#eee;padding:11px 22px;border-radius:8px;
    font-size:.88rem;box-shadow:0 4px 16px rgba(0,0,0,.5);
    opacity:0;pointer-events:none;transition:opacity .3s;z-index:999}
  #toast.show{opacity:1}
  #toast.ok{border-left:4px solid #2d6a4f}
  #toast.err{border-left:4px solid #e94560}

  /* ── File-load hidden input ─────────────────────────────── */
  #file-input{display:none}
</style>
</head>
<body>

<header>
  <h1>🌾 FS25 Crop Calendar Editor</h1>
  <span>Click a month cell to cycle: Idle → Plant → Grow → Harvest → Idle</span>
</header>

<div class="container">

  <!-- ═══ Sidebar ═══════════════════════════════════════════════════ -->
  <aside>
    <h2>Crop Details</h2>

    <div class="field">
      <label>Crop Name (identifier)</label>
      <input id="f-name" type="text" value="myCrop" placeholder="e.g. myCrop">
    </div>
    <div class="field">
      <label>Display Title</label>
      <input id="f-title" type="text" value="My Crop" placeholder="e.g. My Crop">
    </div>
    <div class="field">
      <label>Preset</label>
      <select id="f-preset">
        <option value="grain">Grain (wheat, barley, rye…)</option>
        <option value="row_crop">Row Crop (corn/maize…)</option>
        <option value="root_crop">Root Crop (potato, sugarbeet…)</option>
        <option value="oilseed">Oilseed (canola, sunflower…)</option>
        <option value="legume">Legume (soybean, pea…)</option>
        <option value="grass">Grass / Hay</option>
      </select>
    </div>

    <div class="btn-group">
      <button class="btn btn-primary"   onclick="saveConfig()">💾 Save Config (JSON)</button>
      <button class="btn btn-secondary" onclick="exportHtml()">📄 Export Calendar HTML</button>
      <label  class="btn btn-outline"   for="file-input">📂 Load Config…</label>
      <input  id="file-input" type="file" accept=".json" onchange="loadConfig(event)">
      <button class="btn btn-outline"   onclick="clearAll()">🗑 Clear All Months</button>
    </div>
  </aside>

  <!-- ═══ Main calendar ═════════════════════════════════════════════ -->
  <main>
    <div class="section-title">Growing Season Calendar</div>

    <div class="legend">
      <div class="legend-item"><div class="swatch sw-idle"></div>   Idle</div>
      <div class="legend-item"><div class="swatch sw-plant"></div>  Planting (P)</div>
      <div class="legend-item"><div class="swatch sw-grow"></div>   Growing (G)</div>
      <div class="legend-item"><div class="swatch sw-harvest"></div>Harvesting (H)</div>
      <span class="tip">Right-click or double-click to reset a cell</span>
    </div>

    <div class="calendar-wrap">
      <table class="cal" id="cal-table">
        <!-- Built by JS -->
      </table>
    </div>
  </main>
</div>

<div id="toast"></div>

<script>
/* ── Constants ─────────────────────────────────────────────────────── */
const MONTHS  = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const ZONES   = ["temperate","continental","dry","tropical","cold"];
const STATES  = ["idle","plant","grow","harvest"];
const LABELS  = {idle:"·", plant:"P", grow:"G", harvest:"H"};

/* ── State ─────────────────────────────────────────────────────────── */
// cells[zone][month1..12] = "idle"|"plant"|"grow"|"harvest"
const cells = {};
ZONES.forEach(z => {
  cells[z] = {};
  for (let m = 1; m <= 12; m++) cells[z][m] = "idle";
});

/* ── Build grid ────────────────────────────────────────────────────── */
function buildGrid() {
  const tbl = document.getElementById("cal-table");
  tbl.innerHTML = "";

  // Header row
  const hdr = tbl.insertRow();
  const thZ = document.createElement("th");
  thZ.className = "zone-head";
  thZ.textContent = "Zone / Month";
  hdr.appendChild(thZ);
  MONTHS.forEach(m => {
    const th = document.createElement("th");
    th.textContent = m;
    hdr.appendChild(th);
  });

  // Zone rows
  ZONES.forEach(zone => {
    const row = tbl.insertRow();
    const lbl = row.insertCell();
    lbl.className = "zone-label";
    lbl.textContent = zone.charAt(0).toUpperCase() + zone.slice(1);

    for (let m = 1; m <= 12; m++) {
      const td = row.insertCell();
      td.className = "cell";
      td.dataset.zone = zone;
      td.dataset.month = m;
      td.addEventListener("click", onCellClick);
      td.addEventListener("contextmenu", e => { e.preventDefault(); resetCell(zone, m); });
      td.addEventListener("dblclick", () => resetCell(zone, m));
      updateCell(zone, m);
    }
  });
}

function updateCell(zone, month) {
  const state = cells[zone][month];
  const td = document.querySelector(`td[data-zone="${zone}"][data-month="${month}"]`);
  if (!td) return;
  td.className = `cell ${state}`;
  td.textContent = LABELS[state];
}

function onCellClick(e) {
  const zone  = e.currentTarget.dataset.zone;
  const month = parseInt(e.currentTarget.dataset.month, 10);
  const cur   = cells[zone][month];
  const next  = STATES[(STATES.indexOf(cur) + 1) % STATES.length];
  cells[zone][month] = next;
  updateCell(zone, month);
}

function resetCell(zone, month) {
  cells[zone][month] = "idle";
  updateCell(zone, month);
}

function clearAll() {
  ZONES.forEach(z => { for (let m=1;m<=12;m++) cells[z][m]="idle"; });
  ZONES.forEach(z => { for (let m=1;m<=12;m++) updateCell(z,m); });
  toast("All months cleared", "ok");
}

/* ── Serialise / deserialise ───────────────────────────────────────── */
function getCalendar() {
  return ZONES.map(zone => ({
    zone,
    planting_months:  monthsForState(zone,"plant"),
    growing_months:   monthsForState(zone,"grow"),
    harvesting_months:monthsForState(zone,"harvest"),
  })).filter(e => e.planting_months.length || e.growing_months.length || e.harvesting_months.length);
}

function monthsForState(zone, state) {
  const out = [];
  for (let m=1;m<=12;m++) if (cells[zone][m]===state) out.push(m);
  return out;
}

function applyCalendar(calArr) {
  ZONES.forEach(z => { for (let m=1;m<=12;m++) cells[z][m]="idle"; });
  (calArr||[]).forEach(e => {
    (e.planting_months||[]).forEach(m  => cells[e.zone][m]="plant");
    (e.growing_months||[]).forEach(m   => cells[e.zone][m]="grow");
    (e.harvesting_months||[]).forEach(m=> cells[e.zone][m]="harvest");
  });
  ZONES.forEach(z => { for (let m=1;m<=12;m++) updateCell(z,m); });
}

function buildPayload() {
  return {
    name:    document.getElementById("f-name").value.trim() || "myCrop",
    title:   document.getElementById("f-title").value.trim() || "My Crop",
    preset:  document.getElementById("f-preset").value,
    calendar: getCalendar(),
  };
}

/* ── API calls ─────────────────────────────────────────────────────── */
async function post(url, body) {
  const r = await fetch(url, {
    method:"POST",
    headers:{"Content-Type":"application/json"},
    body:JSON.stringify(body),
  });
  return r.json();
}

async function saveConfig() {
  const data = await post("/api/save", buildPayload());
  if (data.ok) toast(`✅ Saved → ${data.path}`, "ok");
  else         toast(`❌ ${data.error}`, "err");
}

async function exportHtml() {
  const data = await post("/api/export-html", buildPayload());
  if (data.ok) {
    toast(`✅ Exported → ${data.path}`, "ok");
    // Open the exported HTML in a new tab
    const blob = new Blob([data.html], {type:"text/html"});
    window.open(URL.createObjectURL(blob), "_blank");
  } else {
    toast(`❌ ${data.error}`, "err");
  }
}

function loadConfig(evt) {
  const file = evt.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = e => {
    try {
      const cfg = JSON.parse(e.target.result);
      document.getElementById("f-name").value  = cfg.name  || "";
      document.getElementById("f-title").value = cfg.title || "";
      if (cfg.preset) document.getElementById("f-preset").value = cfg.preset;
      applyCalendar(cfg.calendar || []);
      toast(`📂 Loaded: ${file.name}`, "ok");
    } catch {
      toast("❌ Invalid JSON file", "err");
    }
  };
  reader.readAsText(file);
  evt.target.value = "";   // allow re-selecting the same file
}

/* ── Toast ─────────────────────────────────────────────────────────── */
let _toastTimer;
function toast(msg, type="ok") {
  const el = document.getElementById("toast");
  el.textContent = msg;
  el.className   = `show ${type}`;
  clearTimeout(_toastTimer);
  _toastTimer = setTimeout(() => el.className = "", 3500);
}

/* ── Init ───────────────────────────────────────────────────────────── */
buildGrid();
</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# HTTP request handler
# ---------------------------------------------------------------------------

class _Handler(BaseHTTPRequestHandler):
    """Minimal HTTP handler for the crop-calendar SPA."""

    output_dir: Path = Path("./output")   # set by server factory

    # Suppress default access-log noise
    def log_message(self, fmt: str, *args: Any) -> None:  # noqa: ANN401
        pass

    # ── routing ────────────────────────────────────────────────────────
    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path in ("/", "/index.html"):
            self._send_html(_SPA_HTML)
        elif parsed.path == "/api/presets":
            self._send_json({
                "presets": list(CROP_PRESETS.keys()),
                "zones": CLIMATE_ZONES,
            })
        elif parsed.path == "/api/load":
            qs = parse_qs(parsed.query)
            fp = qs.get("path", [None])[0]
            if not fp:
                self._send_json({"ok": False, "error": "No path provided"}, 400)
                return
            try:
                cfg = CropConfig.from_json(fp)
                self._send_json({"ok": True, "config": cfg.to_dict()})
            except Exception as exc:
                self._send_json({"ok": False, "error": str(exc)}, 500)
        else:
            self._send_json({"error": "Not found"}, 404)

    def do_POST(self) -> None:
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length)
        try:
            data = json.loads(body)
        except json.JSONDecodeError:
            self._send_json({"ok": False, "error": "Invalid JSON body"}, 400)
            return

        parsed = urlparse(self.path)
        if parsed.path == "/api/save":
            self._handle_save(data)
        elif parsed.path == "/api/export-html":
            self._handle_export_html(data)
        else:
            self._send_json({"error": "Not found"}, 404)

    # ── handlers ───────────────────────────────────────────────────────
    def _handle_save(self, data: dict[str, Any]) -> None:
        try:
            crop = _config_from_api(data)
            out = ensure_dir(self.output_dir)
            dest = out / f"{crop.name}_config.json"
            crop.to_json(dest)
            self._send_json({"ok": True, "path": str(dest.resolve())})
        except Exception as exc:
            self._send_json({"ok": False, "error": str(exc)}, 500)

    def _handle_export_html(self, data: dict[str, Any]) -> None:
        try:
            crop = _config_from_api(data)
            out = ensure_dir(self.output_dir)
            dest = generate_calendar_html(crop, out)
            html_content = dest.read_text(encoding="utf-8")
            self._send_json({
                "ok": True,
                "path": str(dest.resolve()),
                "html": html_content,
            })
        except Exception as exc:
            self._send_json({"ok": False, "error": str(exc)}, 500)

    # ── response helpers ────────────────────────────────────────────────
    def _send_html(self, html: str) -> None:
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_json(self, payload: Any, status: int = 200) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _config_from_api(data: dict[str, Any]) -> CropConfig:
    """Build a CropConfig from the JSON payload sent by the SPA."""
    name    = data.get("name", "myCrop")
    title   = data.get("title", name)
    preset  = data.get("preset", "grain")
    crop    = CropConfig(name=name, title=title, preset=preset)
    crop.apply_preset()

    calendar_raw = data.get("calendar", [])
    crop.calendar = [
        CalendarEntry(
            zone=e["zone"],
            planting_months=e.get("planting_months", []),
            growing_months=e.get("growing_months", []),
            harvesting_months=e.get("harvesting_months", []),
        )
        for e in calendar_raw
    ]
    return crop


# ---------------------------------------------------------------------------
# Server factory & entry point
# ---------------------------------------------------------------------------

def make_server(port: int, output_dir: str | Path) -> HTTPServer:
    """Create and return the HTTPServer bound to *port*."""

    class _BoundHandler(_Handler):
        pass

    _BoundHandler.output_dir = ensure_dir(output_dir)
    return HTTPServer(("127.0.0.1", port), _BoundHandler)


def main(argv: Optional[list[str]] = None) -> None:  # noqa: UP007
    import argparse

    parser = argparse.ArgumentParser(
        prog="crop_calendar",
        description="FS25 Crop Calendar – web-based editor",
    )
    parser.add_argument(
        "--port", type=int, default=8080,
        help="Port for the local web server (default: 8080)",
    )
    parser.add_argument(
        "--output", default="./output",
        help="Directory where exported files are saved (default: ./output)",
    )
    parser.add_argument(
        "--no-browser", action="store_true",
        help="Do not open the browser automatically",
    )
    args = parser.parse_args(argv)

    server = make_server(args.port, args.output)
    url = f"http://127.0.0.1:{args.port}/"
    print(f"🌾  FS25 Crop Calendar  →  {url}")
    print(f"    Exports saved to    →  {Path(args.output).resolve()}")
    print("    Press Ctrl-C to stop.\n")

    if not args.no_browser:
        threading.Timer(0.4, lambda: webbrowser.open(url)).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
